server:
  port: 8080

spring:
  application:
    name: hello-world-metrics

management:
  endpoints:
    web:
      exposure:
        include: health,metrics,prometheus,info
      base-path: /actuator
  endpoint:
    health:
      show-details: always
    metrics:
      enabled: true
  metrics:
    export:
      prometheus:
        enabled: true
  health:
    defaults:
      enabled: true 