{{- if .Values.podDisruptionBudget.enabled }}
apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: {{ include "hello-world-metrics.fullname" . }}
  labels:
    {{- include "hello-world-metrics.labels" . | nindent 4 }}
spec:
  minAvailable: {{ .Values.podDisruptionBudget.minAvailable }}
  selector:
    matchLabels:
      {{- include "hello-world-metrics.selectorLabels" . | nindent 6 }}
{{- end }} 