{{- if .Values.monitoring.podMonitor.enabled }}
apiVersion: monitoring.googleapis.com/v1
kind: PodMonitoring
metadata:
  name: {{ include "hello-world-metrics.fullname" . }}
  labels:
    {{- include "hello-world-metrics.labels" . | nindent 4 }}
  {{- with .Values.monitoring.podMonitor.labels }}
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  selector:
    matchLabels:
      {{- include "hello-world-metrics.selectorLabels" . | nindent 6 }}
  endpoints:
  - port: http
    path: /actuator/prometheus
    interval: {{ .Values.monitoring.podMonitor.interval }}
{{- end }} 